// This file is auto-generated by @hey-api/openapi-ts

export type LoginInput = {
    email: string;
    password: string;
};

export type LoginResponse = {
    token: string;
};

export type Profile = {
    id: string;
    email: string;
    name: string;
};

export type _Error = {
    code: string;
    message: string;
};

export type LoginData = {
    body: LoginInput;
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginErrors = {
    /**
     * Invalid credentials
     */
    401: _Error;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Login successful
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile';
};

export type GetProfileErrors = {
    /**
     * Unauthorized
     */
    401: _Error;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
    /**
     * Profile retrieved successfully
     */
    200: Profile;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type ClientOptions = {
    baseUrl: 'https://api.example.com/v1' | (string & {});
};