import '@/styles/global.css';

import type { Metadata } from 'next';
import { notoSansJP } from '@/configs/next-font.config';
import RootProvider from '@/providers/root.provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${notoSansJP.variable} antialiased`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
